// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPOMGXrctAetCgsklQ1s05Pk2OU5Zrj5Y',
    appId: '1:297525638515:web:c0f72e2e98c0e301274106',
    messagingSenderId: '297525638515',
    projectId: 'belajari-ed20f',
    authDomain: 'belajari-ed20f.firebaseapp.com',
    databaseURL: 'https://belajari-ed20f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'belajari-ed20f.appspot.com',
    measurementId: 'G-XR5FCG8NHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKGF1gAxMkik7w5Iq1AejMxq9uMb0EXfw',
    appId: '1:297525638515:android:6ce8b66b73ca31ad274106',
    messagingSenderId: '297525638515',
    projectId: 'belajari-ed20f',
    databaseURL: 'https://belajari-ed20f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'belajari-ed20f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTUFQbwxRUWUDAyBDpHNJWDoLi6Bd6HJM',
    appId: '1:297525638515:ios:083fd2d6a7da6f0a274106',
    messagingSenderId: '297525638515',
    projectId: 'belajari-ed20f',
    databaseURL: 'https://belajari-ed20f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'belajari-ed20f.appspot.com',
    iosBundleId: 'com.example.belajari',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTUFQbwxRUWUDAyBDpHNJWDoLi6Bd6HJM',
    appId: '1:297525638515:ios:083fd2d6a7da6f0a274106',
    messagingSenderId: '297525638515',
    projectId: 'belajari-ed20f',
    databaseURL: 'https://belajari-ed20f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'belajari-ed20f.appspot.com',
    iosBundleId: 'com.example.belajari',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPOMGXrctAetCgsklQ1s05Pk2OU5Zrj5Y',
    appId: '1:297525638515:web:8c2993c5a8710a71274106',
    messagingSenderId: '297525638515',
    projectId: 'belajari-ed20f',
    authDomain: 'belajari-ed20f.firebaseapp.com',
    databaseURL: 'https://belajari-ed20f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'belajari-ed20f.appspot.com',
    measurementId: 'G-J9VHZCRXND',
  );
}
